version: "2.1"

executors:
  # `main` uses the `cimg/go:1.15` docker image.
  main:
    docker:
      - image: cimg/go:1.15

  # `base` uses the `cimg/base` docker image.
  base:
    docker:
      - image: cimg/base:2020.07

  # `macos` uses the Windows machine image.
  macos:
    macos:
      xcode: 11.5.0
      resource_class: medium

  # `windows` uses the Windows machine image.
  windows:
    machine:
      image: "windows-server-2019-vs2019:stable"
      resource_class: "windows.medium"
      shell: "powershell.exe -ExecutionPolicy Bypass"


jobs:

  # `test_go` tests the GRW source code.
  test_go:
    executor: main
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run: make fmt
      - run: make imports
      - run: make test_go
      - run: git diff --exit-code

  # `test_cli` tests the GRW executable.
  test_cli:
    executor: main
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run: make tidy
      - run: make bin/grw
      - run: make test_cli

  # `test_javascript` tests the GRW JavaScript library.
  test_javascript:
    executor: main
    steps:
      - run: sudo chown -R circleci /go/src
      - run: sudo npm install -g n
      - run: sudo n v11.15.0
      - run: sudo npm install --global source-map-support
      - run: make deps_gopherjs
      - run: make deps_javascript
      - run:
          name: Install support for syscalls
          command: |
            cd /go/src/github.com/gopherjs/gopherjs/node-syscall
            echo '{"engines" : {"node" : ">=11.15.0 <12.0.0"},"dependencies": {"node-gyp": "^5.0.3"}}' > package.json
            npm install .
            node_modules/node-gyp/bin/node-gyp.js rebuild
            mkdir -p ~/.node_libraries/
            cp build/Release/syscall.node ~/.node_libraries/syscall.node
      - run: npm run test:unit:clean

  # `build_cli` builds the GRW executable.
  build_cli:
    executor: main
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run: make tidy
      - run: make build_release
      - run: rm -f bin/gox
      - run: sudo make deps_arm
      - run: make build_so
      - store_artifacts:
          path: bin
          destination: /
      - persist_to_workspace:
          root: bin
          paths:
            - grw_darwin_amd64
            - grw_linux_386
            - grw_linux_amd64
            - grw_linux_arm
            - grw_linux_arm64
            - grw_windows_386.exe
            - grw_windows_amd64.exe

  # `examples` runs the GRW examples.
  examples:
    executor: base
    steps:
      - run: sudo chown -R circleci /go/src
      - run: sudo npm install -g n
      - run:
          name: Install Node 11.15.0
          command: sudo n 11.15.0
      - run: make deps_gopherjs
      - run: make deps_javascript
      - run: npm run build:clean
      - run:
          name: Install support for syscalls
          command: |
            cd /go/src/github.com/gopherjs/gopherjs/node-syscall
            echo '{"engines" : {"node" : ">=11.15.0 <12.0.0"},"dependencies": {"node-gyp": "^5.0.3"}}' > package.json
            npm install .
            node_modules/node-gyp/bin/node-gyp.js rebuild
            mkdir -p ~/.node_libraries/
            cp build/Release/syscall.node ~/.node_libraries/syscall.node
      - run: make run_example_c
      - run: make run_example_cpp
      - run: make run_example_javascript
      - run: make run_example_python

  # `verify_linux` verifys the linux build
  verify_linux:
    executor: base
    steps:
      - attach_workspace:
          at: bin
      - run: bin/grw_linux_386 --help
      - run: bin/grw_linux_amd64 --help

  # `verify_macos` verifys the macOS build
  verify_macos:
    executor: macos
    steps:
      - attach_workspace:
          at: bin
      - run: bin/grw_darwin_amd64 --help

  # `verify_windows` verifys the windows build
  verify_windows:
    executor: windows
    steps:
      - attach_workspace:
          at: bin
      - run: bin/grw_windows_386.exe --help
      - run: bin/grw_windows_amd64.exe --help

workflows:
  version: 2
  main:
    jobs:
      - test_go
      - test_cli
      - test_javascript
      - build
      - verify_linux:
          requires:
            - build
      - verify_macos:
          requires:
            - build
      - verify_windows:
          requires:
            - build
